package hu.wolfman.fishscreensaver.frame;

import hu.wolfman.fishscreensaver.util.ImageUtil;

import javax.swing.*;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;

public class RajzPanel extends JPanel {
    private final Image kep = ImageUtil.getImage("/kepek/hatter.jpg");
    private Vezerlo vezerlo;

    public RajzPanel() {
        initComponents();
        hideCursor();
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    private void hideCursor() {
        // Source: https://stackoverflow.com/questions/1984071/how-to-hide-cursor-in-a-swing-application
        BufferedImage cursorImg = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
        Cursor blankCursor = Toolkit.getDefaultToolkit()
                .createCustomCursor(cursorImg, new Point(0, 0), "blank cursor");
        this.setCursor(blankCursor);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        int kezdoX = 0;
        int kezdoY = 0;
        int szelesseg = this.getWidth();
        int magassag = this.getHeight();
        g.drawImage(kep, kezdoX, kezdoY, szelesseg, magassag, null);
        if (vezerlo != null) {
            vezerlo.rajzol(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
